import Hosts from '../../../../Common/Constants/Roblox.Common.Constants/Hosts';
import { DYNAMIC_LOGVARIABLE, FASTFLAGVARIABLE, LOGVARIABLE, SYNCHRONIZED_LOGGROUP, SYNCHRONIZED_LOGVARIABLE } from './FastLog';

export class FastLogGlobal {
	public static Init() {
		LOGVARIABLE('GumePersistince', 6);
		LOGVARIABLE('TheInternalSystem', 6);
		LOGVARIABLE('AandBTusting', 6);
		LOGVARIABLE('SIMPLEPING', 6);
		LOGVARIABLE('Protocol77', 6);
		LOGVARIABLE('DataStoreV2', 7);
		LOGVARIABLE('DataStore', 7);
		LOGVARIABLE('EphemeralCountersV2', 7);
		LOGVARIABLE('EphemeralCounters', 7);
		LOGVARIABLE('Stats', 7);
		LOGVARIABLE('Grid', 7);
		LOGVARIABLE('dmp', 7);
		LOGVARIABLE('CsrfAPIV1', 7);
		LOGVARIABLE('ClientSettingsAPIV1', 7);
		LOGVARIABLE('WWWAuthV1', 7);
		LOGVARIABLE('ClientTelementry', 7);
		DYNAMIC_LOGVARIABLE('Tasks', 7);
		SYNCHRONIZED_LOGVARIABLE(Hosts['Apex'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['WebHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ApiProxyHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['StaticCDN'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['JavaScriptCDN'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CSSCDN'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ImagesCDN'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['SetupCDN'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EphemeralCountersService'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EphemeralCountersV2'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TemporaryImagesCDN'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['VersionCompatibilityService'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ClientSettingsService'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AssetGameHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GamePersistenceHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['MarketplaceService'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['MetricsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ApiGatewayHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ApiGatewayCDNHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DEPRECATED_CaptchaHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AuthenticationHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['LocaleHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AbTestingHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['UsersHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TSVHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['LatencyMeasurementsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ChatHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ContactsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['NotificationsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AccountSettingsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AdsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TradesHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['FriendsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PrivateMessagesHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EconomyHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GamesHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['RealTimeHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ThumbsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PresenceHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GroupsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AccountInformationHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['BadgesHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DeveloperForumHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PremiumFeaturesHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ClientSettingsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ClientSettingsCDNHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AdConfigurationHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ClientTelementryServiceHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AssetsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AvatarHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['BillingHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CatalogHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CdnProvidersHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ChatModerationHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ContentStoreHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DevelopHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DiscussionsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EconomyCreatorStatsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['EngagementPayoutsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['FollowingsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['G18NHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GameJoinHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['GroupsModerationHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['InventoryHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ItemConfigurationHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['LocalizationTablesHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PointsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PublishHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PunishmentsService'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ShareHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TextFilterHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ThemesHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ThumbnailsResizerHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TranslationRolesHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['TranslationsHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['UserModerationHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['VoiceHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['FilesService'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['MetricsInternalWebsiteHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AbTestingService'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['AdminWebsiteHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CSWebsiteHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['ComApisCDNHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['PointsServiceHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['UsersServiceHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DataHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['MidasHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['DEPRECATED_ApiGatewayRCSHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['NomadHost'], 6);
		SYNCHRONIZED_LOGVARIABLE(Hosts['CSRHost'], 6);

		FASTFLAGVARIABLE('RequireGlobalHTTPS', true);
	}

	public static IncludeHostLogLevels() {
		SYNCHRONIZED_LOGGROUP(Hosts['Apex']);
		SYNCHRONIZED_LOGGROUP(Hosts['WebHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ApiProxyHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['StaticCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['JavaScriptCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['CSSCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['ImagesCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['SetupCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['EphemeralCountersService']);
		SYNCHRONIZED_LOGGROUP(Hosts['EphemeralCountersV2']);
		SYNCHRONIZED_LOGGROUP(Hosts['TemporaryImagesCDN']);
		SYNCHRONIZED_LOGGROUP(Hosts['VersionCompatibilityService']);
		SYNCHRONIZED_LOGGROUP(Hosts['ClientSettingsService']);
		SYNCHRONIZED_LOGGROUP(Hosts['AssetGameHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GamePersistenceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['MarketplaceService']);
		SYNCHRONIZED_LOGGROUP(Hosts['MetricsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ApiGatewayHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ApiGatewayCDNHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DEPRECATED_CaptchaHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AuthenticationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['LocaleHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AbTestingHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['UsersHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TSVHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['LatencyMeasurementsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ChatHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ContactsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['NotificationsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AccountSettingsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AdsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TradesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['FriendsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PrivateMessagesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['EconomyHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GamesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['RealTimeHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ThumbsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PresenceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GroupsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AccountInformationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['BadgesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DeveloperForumHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PremiumFeaturesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ClientSettingsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ClientSettingsCDNHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AdConfigurationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ClientTelementryServiceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AssetsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AvatarHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['BillingHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['CatalogHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['CdnProvidersHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ChatModerationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ContentStoreHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DevelopHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DiscussionsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['EconomyCreatorStatsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['EngagementPayoutsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['FollowingsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['G18NHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GameJoinHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['GroupsModerationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['InventoryHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ItemConfigurationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['LocalizationTablesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PointsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PublishHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PunishmentsService']);
		SYNCHRONIZED_LOGGROUP(Hosts['ShareHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TextFilterHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ThemesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ThumbnailsResizerHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TranslationRolesHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['TranslationsHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['UserModerationHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['VoiceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['FilesService']);
		SYNCHRONIZED_LOGGROUP(Hosts['MetricsInternalWebsiteHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['AbTestingService']);
		SYNCHRONIZED_LOGGROUP(Hosts['AdminWebsiteHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['CSWebsiteHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['ComApisCDNHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['PointsServiceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['UsersServiceHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DataHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['MidasHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['DEPRECATED_ApiGatewayRCSHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['NomadHost']);
		SYNCHRONIZED_LOGGROUP(Hosts['CSRHost']);
	}
}
