import { Request, Response } from 'express';

export default {
	method: 'all',
	func: async (_request: Request, response: Response) => {
		return response.status(200).send({
			config: {
				ACL: { Enabled: false, PolicyTTL: 30000000000, ReplicationToken: '', TokenTTL: 30000000000 },
				Addresses: { HTTP: '0.0.0.0', RPC: '0.0.0.0', Serf: '0.0.0.0' },
				AdvertiseAddrs: { HTTP: '138.68.164.172:4646', RPC: '10.106.0.4:4647', Serf: '10.106.0.4:4648' },
				Audit: { Enabled: null, Filters: null, Sinks: null },
				Autopilot: {
					CleanupDeadServers: null,
					DisableUpgradeMigration: null,
					EnableCustomUpgrades: null,
					EnableRedundancyZones: null,
					LastContactThreshold: 200000000,
					MaxTrailingLogs: 250,
					MinQuorum: 0,
					ServerStabilizationTime: 10000000000,
				},
				BindAddr: '0.0.0.0',
				Client: {
					AllocDir: '',
					BindWildcardDefaultHostNetwork: true,
					BridgeNetworkName: '',
					BridgeNetworkSubnet: '',
					CNIConfigDir: '',
					CNIPath: '',
					ChrootEnv: {},
					ClientMaxPort: 14512,
					ClientMinPort: 14000,
					CpuCompute: 0,
					DisableRemoteExec: false,
					Enabled: false,
					GCDiskUsageThreshold: 80.0,
					GCInodeUsageThreshold: 70.0,
					GCInterval: 60000000000,
					GCMaxAllocs: 50,
					GCParallelDestroys: 2,
					HostNetworks: null,
					HostVolumes: null,
					MaxKillTimeout: '30s',
					MemoryMB: 0,
					Meta: {},
					NetworkInterface: '',
					NetworkSpeed: 0,
					NoHostUUID: true,
					NodeClass: '',
					Options: {},
					Reserved: { CPU: 0, DiskMB: 0, MemoryMB: 0, ReservedPorts: '' },
					ServerJoin: { RetryInterval: 30000000000, RetryJoin: [], RetryMaxAttempts: 0, StartJoin: null },
					Servers: null,
					StateDir: '',
					TemplateConfig: { DisableSandbox: false, FunctionBlacklist: null, FunctionDenylist: ['plugin'] },
				},
				Consul: {
					Addr: '127.0.0.1:8500',
					AllowUnauthenticated: true,
					Auth: '',
					AutoAdvertise: true,
					CAFile: '',
					CertFile: '',
					ChecksUseAdvertise: false,
					ClientAutoJoin: true,
					ClientHTTPCheckName: 'Nomad Client HTTP Check',
					ClientServiceName: 'nomad-client',
					EnableSSL: false,
					GRPCAddr: '',
					KeyFile: '',
					Namespace: '',
					ServerAutoJoin: true,
					ServerHTTPCheckName: 'Nomad Server HTTP Check',
					ServerRPCCheckName: 'Nomad Server RPC Check',
					ServerSerfCheckName: 'Nomad Server Serf Check',
					ServerServiceName: 'nomad',
					ShareSSL: null,
					Tags: null,
					Timeout: 5000000000,
					Token: '',
					VerifySSL: true,
				},
				DataDir: '/mnt/nomad/',
				Datacenter: 'ark-1773.eu-west',
				DevMode: false,
				DisableAnonymousSignature: false,
				DisableUpdateCheck: false,
				EnableDebug: false,
				EnableSyslog: false,
				Files: ['/etc/nomad.d/nomad.hcl', '/etc/nomad.d/server.hcl'],
				HTTPAPIResponseHeaders: {},
				LeaveOnInt: false,
				LeaveOnTerm: false,
				Limits: {
					HTTPMaxConnsPerClient: 100,
					HTTPSHandshakeTimeout: '5s',
					RPCHandshakeTimeout: '5s',
					RPCMaxConnsPerClient: 100,
				},
				LogFile: '',
				LogJson: false,
				LogLevel: 'INFO',
				LogRotateBytes: 0,
				LogRotateDuration: '',
				LogRotateMaxFiles: 0,
				NodeName: '',
				PluginDir: '/mnt/nomad/plugins',
				Plugins: null,
				Ports: { HTTP: 4646, RPC: 4647, Serf: 4648 },
				Region: 'eu-west-1223',
				Sentinel: { Imports: null },
				Server: {
					AuthoritativeRegion: '',
					BootstrapExpect: 3,
					CSIPluginGCThreshold: '',
					CSIVolumeClaimGCThreshold: '',
					DataDir: '',
					DefaultSchedulerConfig: null,
					DeploymentGCThreshold: '',
					EnableEventBroker: true,
					Enabled: true,
					EnabledSchedulers: null,
					EvalGCThreshold: '',
					EventBufferSize: 100,
					HeartbeatGrace: 0,
					JobGCInterval: '',
					JobGCThreshold: '',
					MaxHeartbeatsPerSecond: 0.0,
					MinHeartbeatTTL: 0,
					NodeGCThreshold: '',
					NonVotingServer: false,
					NumSchedulers: null,
					ProtocolVersion: 0,
					RaftMultiplier: null,
					RaftProtocol: 0,
					RedundancyZone: '',
					RejoinAfterLeave: false,
					RetryInterval: 0,
					RetryJoin: [],
					RetryMaxAttempts: 0,
					ServerJoin: {
						RetryInterval: 30000000000,
						RetryJoin: [
							'provider=digitalocean region=eu-west-1223 tag_name=nomad-server api_token=fb0b9f83cb2db38fd3fd00fb8f3d8c64af9911c1176b791936514da75c61336f',
						],
						RetryMaxAttempts: 0,
						StartJoin: null,
					},
					StartJoin: [],
					UpgradeVersion: '',
				},
				SyslogFacility: 'LOCAL0',
				TLSConfig: {
					CAFile: '',
					CertFile: '',
					Checksum: '',
					EnableHTTP: false,
					EnableRPC: false,
					KeyFile: '',
					KeyLoader: {},
					RPCUpgradeMode: false,
					TLSCipherSuites: '',
					TLSMinVersion: '',
					TLSPreferServerCipherSuites: false,
					VerifyHTTPSClient: false,
					VerifyServerHostname: false,
				},
				Telemetry: {
					CirconusAPIApp: '',
					CirconusAPIToken: '',
					CirconusAPIURL: '',
					CirconusBrokerID: '',
					CirconusBrokerSelectTag: '',
					CirconusCheckDisplayName: '',
					CirconusCheckForceMetricActivation: '',
					CirconusCheckID: '',
					CirconusCheckInstanceID: '',
					CirconusCheckSearchTag: '',
					CirconusCheckSubmissionURL: '',
					CirconusCheckTags: '',
					CirconusSubmissionInterval: '',
					CollectionInterval: '1s',
					DataDogAddr: '',
					DataDogTags: null,
					DisableDispatchedJobSummaryMetrics: false,
					DisableHostname: false,
					FilterDefault: null,
					PrefixFilter: null,
					PrometheusMetrics: false,
					PublishAllocationMetrics: false,
					PublishNodeMetrics: false,
					StatsdAddr: '',
					StatsiteAddr: '',
					UseNodeName: false,
				},
				Vault: {
					Addr: 'https://vault.service.consul:8200',
					AllowUnauthenticated: true,
					ConnectionRetryIntv: 30000000000,
					Enabled: null,
					Namespace: '',
					Role: '',
					TLSCaFile: '',
					TLSCaPath: '',
					TLSCertFile: '',
					TLSKeyFile: '',
					TLSServerName: '',
					TLSSkipVerify: null,
					TaskTokenTTL: '',
					Token: '',
				},
				Version: {
					Revision: '9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a',
					Version: '1.0.4',
					VersionMetadata: '',
					VersionPrerelease: '',
				},
			},
			member: {
				Addr: '10.106.0.4',
				DelegateCur: 4,
				DelegateMax: 5,
				DelegateMin: 2,
				Name: 'nomad-server-0.eu-west-1223',
				Port: 4648,
				ProtocolCur: 2,
				ProtocolMax: 5,
				ProtocolMin: 1,
				Status: 'alive',
				Tags: {
					port: '4647',
					vsn: '1',
					role: 'nomad',
					raft_vsn: '2',
					region: 'eu-west-1223',
					dc: 'nomad',
					mvn: '1',
					id: '44fee37d-e878-0890-dbcf-f4741c4528c3',
					build: '1.0.4',
					rpc_addr: '10.106.0.4',
					expect: '3',
				},
			},
			stats: {
				nomad: { server: 'true', leader: 'false', leader_addr: '10.106.0.5:4647', bootstrap: 'false', known_regions: '1' },
				raft: {
					last_snapshot_term: '2',
					protocol_version_max: '3',
					snapshot_version_min: '0',
					snapshot_version_max: '1',
					latest_configuration:
						'[{Suffrage:Voter ID:10.106.0.4:4647 Address:10.106.0.4:4647} {Suffrage:Voter ID:10.106.0.5:4647 Address:10.106.0.5:4647} {Suffrage:Voter ID:10.106.0.2:4647 Address:10.106.0.2:4647}]',
					last_log_index: '32215',
					last_log_term: '2',
					last_snapshot_index: '24580',
					state: 'Follower',
					term: '2',
					last_contact: '45.94862ms',
					latest_configuration_index: '0',
					num_peers: '2',
					commit_index: '32215',
					applied_index: '32215',
					protocol_version: '2',
					fsm_pending: '0',
					protocol_version_min: '0',
				},
				serf: {
					query_queue: '0',
					failed: '0',
					left: '0',
					member_time: '4',
					query_time: '1',
					event_queue: '0',
					encrypted: 'false',
					coordinate_resets: '0',
					members: '3',
					health_score: '0',
					event_time: '1',
					intent_queue: '0',
				},
				runtime: {
					goroutines: '56',
					cpu_count: '1',
					'kernel.name': 'linux',
					arch: 'amd64',
					version: 'go1.15.6',
					max_procs: '1',
				},
				vault: { tracked_for_revoked: '0', token_ttl: '0s', token_expire_time: '' },
			},
		});
	},
};
