import { Request, Response } from 'express';

export default {
	method: 'all',
	func: async (_request: Request, response: Response) => {
		return response.status(200).send([
			{
				ID: '1dd5ee98-02fa-6cf6-fcda-5cee6e3438be',
				EvalID: '8a760614-d54c-63f9-5ac8-2c3460fa0a16',
				Name: 'dev-ark.ark[0]',
				Namespace: 'default',
				NodeID: '64cf1f24-7a11-81e1-cb6b-5211424eab8b',
				NodeName: 'nomad-clients-dev-b-jqsj',
				JobID: 'sea-ark13',
				JobType: 'service',
				JobVersion: 2,
				TaskGroup: 'ark',
				DesiredStatus: 'run',
				DesiredDescription: '',
				ClientStatus: 'running',
				ClientDescription: 'Tasks are running',
				DesiredTransition: { Migrate: null, Reschedule: null, ForceReschedule: null },
				TaskStates: {
					ark: {
						State: 'running',
						Failed: false,
						Restarts: 0,
						LastRestart: null,
						StartedAt: '2021-05-04T03:30:37.668448541Z',
						FinishedAt: null,
						Events: [
							{
								Type: 'Received',
								Time: 1620099029161819111,
								Message: '',
								DisplayMessage: 'Task received by client',
								Details: {},
								FailsTask: false,
								RestartReason: '',
								SetupError: '',
								DriverError: '',
								ExitCode: 0,
								Signal: 0,
								KillTimeout: 0,
								KillError: '',
								KillReason: '',
								StartDelay: 0,
								DownloadError: '',
								ValidationError: '',
								DiskLimit: 0,
								FailedSibling: '',
								VaultError: '',
								TaskSignalReason: '',
								TaskSignal: '',
								DriverMessage: '',
								GenericSource: '',
							},
							{
								Type: 'Task Setup',
								Time: 1620099029171614724,
								Message: 'Building Task Directory',
								DisplayMessage: 'Building Task Directory',
								Details: { message: 'Building Task Directory' },
								FailsTask: false,
								RestartReason: '',
								SetupError: '',
								DriverError: '',
								ExitCode: 0,
								Signal: 0,
								KillTimeout: 0,
								KillError: '',
								KillReason: '',
								StartDelay: 0,
								DownloadError: '',
								ValidationError: '',
								DiskLimit: 0,
								FailedSibling: '',
								VaultError: '',
								TaskSignalReason: '',
								TaskSignal: '',
								DriverMessage: '',
								GenericSource: '',
							},
							{
								Type: 'Driver',
								Time: 1620099029239416944,
								Message: '',
								DisplayMessage: 'Downloading image',
								Details: { image: 'jippi/ark:latest' },
								FailsTask: false,
								RestartReason: '',
								SetupError: '',
								DriverError: '',
								ExitCode: 0,
								Signal: 0,
								KillTimeout: 0,
								KillError: '',
								KillReason: '',
								StartDelay: 0,
								DownloadError: '',
								ValidationError: '',
								DiskLimit: 0,
								FailedSibling: '',
								VaultError: '',
								TaskSignalReason: '',
								TaskSignal: '',
								DriverMessage: 'Downloading image',
								GenericSource: '',
							},
							{
								Type: 'Started',
								Time: 1620099037668442338,
								Message: '',
								DisplayMessage: 'Task started by client',
								Details: {},
								FailsTask: false,
								RestartReason: '',
								SetupError: '',
								DriverError: '',
								ExitCode: 0,
								Signal: 0,
								KillTimeout: 0,
								KillError: '',
								KillReason: '',
								StartDelay: 0,
								DownloadError: '',
								ValidationError: '',
								DiskLimit: 0,
								FailedSibling: '',
								VaultError: '',
								TaskSignalReason: '',
								TaskSignal: '',
								DriverMessage: '',
								GenericSource: '',
							},
						],
					},
					'log-shipper': {
						State: 'running',
						Failed: false,
						Restarts: 0,
						LastRestart: null,
						StartedAt: '2021-05-04T03:30:29.784936995Z',
						FinishedAt: null,
						Events: [
							{
								Type: 'Received',
								Time: 1620099029162229261,
								Message: '',
								DisplayMessage: 'Task received by client',
								Details: {},
								FailsTask: false,
								RestartReason: '',
								SetupError: '',
								DriverError: '',
								ExitCode: 0,
								Signal: 0,
								KillTimeout: 0,
								KillError: '',
								KillReason: '',
								StartDelay: 0,
								DownloadError: '',
								ValidationError: '',
								DiskLimit: 0,
								FailedSibling: '',
								VaultError: '',
								TaskSignalReason: '',
								TaskSignal: '',
								DriverMessage: '',
								GenericSource: '',
							},
							{
								Type: 'Task Setup',
								Time: 1620099029165867709,
								Message: 'Building Task Directory',
								DisplayMessage: 'Building Task Directory',
								Details: { message: 'Building Task Directory' },
								FailsTask: false,
								RestartReason: '',
								SetupError: '',
								DriverError: '',
								ExitCode: 0,
								Signal: 0,
								KillTimeout: 0,
								KillError: '',
								KillReason: '',
								StartDelay: 0,
								DownloadError: '',
								ValidationError: '',
								DiskLimit: 0,
								FailedSibling: '',
								VaultError: '',
								TaskSignalReason: '',
								TaskSignal: '',
								DriverMessage: '',
								GenericSource: '',
							},
							{
								Type: 'Started',
								Time: 1620099029784931474,
								Message: '',
								DisplayMessage: 'Task started by client',
								Details: {},
								FailsTask: false,
								RestartReason: '',
								SetupError: '',
								DriverError: '',
								ExitCode: 0,
								Signal: 0,
								KillTimeout: 0,
								KillError: '',
								KillReason: '',
								StartDelay: 0,
								DownloadError: '',
								ValidationError: '',
								DiskLimit: 0,
								FailedSibling: '',
								VaultError: '',
								TaskSignalReason: '',
								TaskSignal: '',
								DriverMessage: '',
								GenericSource: '',
							},
						],
					},
				},
				DeploymentStatus: { Healthy: true, Timestamp: '2021-05-04T03:30:52.166325706Z', Canary: false, ModifyIndex: 285276 },
				FollowupEvalID: '',
				RescheduleTracker: null,
				PreemptedAllocations: null,
				PreemptedByAllocation: '',
				CreateIndex: 285270,
				ModifyIndex: 285276,
				CreateTime: 1620099029135746569,
				ModifyTime: 1620099052246960107,
			},
		]);
	},
};
