DROP PROCEDURE IF EXISTS `<CLASSNAME>s_Get<CLASSNAME>IDsBy<FKPROPERTYNAME>`;

CREATE PROCEDURE `<CLASSNAME>s_Get<CLASSNAME>IDsBy<FKPROPERTYNAME>`
(
    <FKPROPERTYNAME>                <FKIDSQLTPE>
)
BEGIN

SELECT
    ID
FROM 
    <CLASSNAME>s
WHERE
    (<FKPROPERTYNAME> = <FKPROPERTYNAME>);

END;