import { Request, Response } from 'express';

export default {
	method: 'all',
	func: async (_request: Request, response: Response) => {
		return response.status(200).send({
			ID: '1dd5ee98-02fa-6cf6-fcda-5cee6e3438be',
			Namespace: 'default',
			EvalID: '8a760614-d54c-63f9-5ac8-2c3460fa0a16',
			Name: 'dev-ark.ark[0]',
			NodeID: '64cf1f24-7a11-81e1-cb6b-5211424eab8b',
			NodeName: 'nomad-clients-dev-b-jqsj',
			JobID: 'sea-ark13',
			Job: {
				Stop: false,
				Region: 'asia-southeast1',
				Namespace: 'default',
				ID: 'sea-ark13',
				ParentID: '',
				Name: 'sea-ark13',
				Type: 'service',
				Priority: 50,
				AllAtOnce: false,
				Datacenters: ['asia-southeast1'],
				Constraints: [{ LTarget: '${node.unique.name}', RTarget: 'nomad-clients-dev.+', Operand: 'regexp' }],
				Affinities: null,
				Spreads: null,
				TaskGroups: [
					{
						Name: 'ark',
						Count: 1,
						Update: {
							Stagger: 30000000000,
							MaxParallel: 1,
							HealthCheck: 'checks',
							MinHealthyTime: 10000000000,
							HealthyDeadline: 300000000000,
							ProgressDeadline: 600000000000,
							AutoRevert: false,
							AutoPromote: false,
							Canary: 0,
						},
						Migrate: { MaxParallel: 1, HealthCheck: 'checks', MinHealthyTime: 10000000000, HealthyDeadline: 300000000000 },
						Constraints: null,
						Scaling: null,
						RestartPolicy: { Attempts: 2, Interval: 1800000000000, Delay: 15000000000, Mode: 'fail' },
						Tasks: [
							{
								Name: 'ark',
								Driver: 'docker',
								User: '',
								Config: { image: 'jippi/ark:latest', hostname: 'dev-ark-${NOMAD_ALLOC_INDEX}' },
								Env: {
									CONSUL_ADDR: 'http://consul.service.consul:8500',
									CONSUL_ENABLE: '1',
									NOMAD_ADDR: 'http://nomad.service.consul:4646',
									NOMAD_ENABLE: '1',
								},
								Services: [
									{
										Name: 'dev-ark',
										TaskName: '',
										PortLabel: 'http',
										AddressMode: 'auto',
										EnableTagOverride: false,
										Tags: ['http', 'ui', 'dev', 'urlprefix-ark-dev.b.apps.mgmt.ghpr.asia:80/', 'latest'],
										CanaryTags: null,
										Checks: [
											{
												Name: 'service: "dev-ark" check',
												Type: 'http',
												Command: '',
												Args: null,
												Path: '/',
												Protocol: '',
												PortLabel: '',
												Expose: false,
												AddressMode: '',
												Interval: 10000000000,
												Timeout: 2000000000,
												InitialStatus: '',
												TLSSkipVerify: false,
												Method: '',
												Header: null,
												CheckRestart: null,
												GRPCService: '',
												GRPCUseTLS: false,
												TaskName: '',
												SuccessBeforePassing: 0,
												FailuresBeforeCritical: 0,
											},
										],
										Connect: null,
										Meta: null,
										CanaryMeta: null,
									},
								],
								Vault: null,
								Templates: null,
								Constraints: null,
								Affinities: null,
								Resources: {
									CPU: 200,
									MemoryMB: 128,
									DiskMB: 0,
									IOPS: 0,
									Networks: [
										{
											Mode: '',
											Device: '',
											CIDR: '',
											IP: '',
											MBits: 1,
											DNS: null,
											ReservedPorts: null,
											DynamicPorts: [{ Label: 'http', Value: 0, To: 0, HostNetwork: 'default' }],
										},
									],
									Devices: null,
								},
								RestartPolicy: { Attempts: 2, Interval: 1800000000000, Delay: 15000000000, Mode: 'fail' },
								DispatchPayload: null,
								Lifecycle: null,
								Meta: null,
								KillTimeout: 5000000000,
								LogConfig: { MaxFiles: 10, MaxFileSizeMB: 10 },
								Artifacts: null,
								Leader: true,
								ShutdownDelay: 0,
								VolumeMounts: null,
								KillSignal: '',
								Kind: '',
								CSIPluginConfig: null,
							},
							{
								Name: 'log-shipper',
								Driver: 'docker',
								User: '',
								Config: {
									args: ['-e', '-c', '/usr/share/fb-config/filebeat.yml'],
									command: 'filebeat',
									hostname: 'log-shipper-dev-ark-${NOMAD_ALLOC_INDEX}',
									image: 'docker.elastic.co/beats/filebeat:6.7.2',
									volumes: ['local/:/usr/share/fb-config'],
								},
								Env: null,
								Services: null,
								Vault: null,
								Templates: [
									{
										SourcePath: '',
										DestPath: 'local/filebeat.yml',
										EmbeddedTmpl:
											'---\nfilebeat.inputs:\n- type: log\n  enabled: true\n  paths:\n    - {{ env "NOMAD_ALLOC_DIR" }}/logs/*.stderr.[0-9]\n    - {{ env "NOMAD_ALLOC_DIR" }}/logs/*.stdout.[0-9]\noutput.logstash:\n    hosts: ["{{ key "service/logstash/host" }}"]\n',
										ChangeMode: 'restart',
										ChangeSignal: '',
										Splay: 5000000000,
										Perms: '0644',
										LeftDelim: '{{',
										RightDelim: '}}',
										Envvars: false,
										VaultGrace: 0,
									},
								],
								Constraints: null,
								Affinities: null,
								Resources: { CPU: 100, MemoryMB: 300, DiskMB: 0, IOPS: 0, Networks: null, Devices: null },
								RestartPolicy: { Attempts: 2, Interval: 1800000000000, Delay: 15000000000, Mode: 'fail' },
								DispatchPayload: null,
								Lifecycle: null,
								Meta: null,
								KillTimeout: 10000000000,
								LogConfig: { MaxFiles: 10, MaxFileSizeMB: 10 },
								Artifacts: null,
								Leader: false,
								ShutdownDelay: 0,
								VolumeMounts: null,
								KillSignal: '',
								Kind: '',
								CSIPluginConfig: null,
							},
						],
						EphemeralDisk: { Sticky: false, SizeMB: 300, Migrate: false },
						Meta: null,
						ReschedulePolicy: {
							Attempts: 0,
							Interval: 0,
							Delay: 30000000000,
							DelayFunction: 'exponential',
							MaxDelay: 3600000000000,
							Unlimited: true,
						},
						Affinities: null,
						Spreads: null,
						Networks: null,
						Services: null,
						Volumes: null,
						ShutdownDelay: null,
						StopAfterClientDisconnect: null,
					},
				],
				Update: {
					Stagger: 30000000000,
					MaxParallel: 1,
					HealthCheck: '',
					MinHealthyTime: 0,
					HealthyDeadline: 0,
					ProgressDeadline: 0,
					AutoRevert: false,
					AutoPromote: false,
					Canary: 0,
				},
				Multiregion: null,
				Periodic: null,
				ParameterizedJob: null,
				Dispatched: false,
				Payload: null,
				Meta: null,
				ConsulToken: '',
				VaultToken: '',
				VaultNamespace: '',
				NomadTokenID: '',
				Status: 'pending',
				StatusDescription: '',
				Stable: false,
				Version: 2,
				SubmitTime: 1620099029128501601,
				CreateIndex: 123032,
				ModifyIndex: 285269,
				JobModifyIndex: 285269,
			},
			TaskGroup: 'ark',
			Resources: {
				CPU: 300,
				MemoryMB: 428,
				DiskMB: 300,
				IOPS: 0,
				Networks: [
					{
						Mode: '',
						Device: 'ens4',
						CIDR: '',
						IP: '10.3.0.12',
						MBits: 1,
						DNS: null,
						ReservedPorts: null,
						DynamicPorts: [{ Label: 'http', Value: 27563, To: 0, HostNetwork: 'default' }],
					},
				],
				Devices: null,
			},
			SharedResources: { CPU: 0, MemoryMB: 0, DiskMB: 300, IOPS: 0, Networks: null, Devices: null },
			TaskResources: {
				'log-shipper': { CPU: 100, MemoryMB: 300, DiskMB: 0, IOPS: 0, Networks: null, Devices: null },
				ark: {
					CPU: 200,
					MemoryMB: 128,
					DiskMB: 0,
					IOPS: 0,
					Networks: [
						{
							Mode: '',
							Device: 'ens4',
							CIDR: '',
							IP: '10.3.0.12',
							MBits: 1,
							DNS: null,
							ReservedPorts: null,
							DynamicPorts: [{ Label: 'http', Value: 27563, To: 0, HostNetwork: 'default' }],
						},
					],
					Devices: null,
				},
			},
			AllocatedResources: {
				Tasks: {
					ark: {
						Cpu: { CpuShares: 200 },
						Memory: { MemoryMB: 128 },
						Networks: [
							{
								Mode: '',
								Device: 'ens4',
								CIDR: '',
								IP: '10.3.0.12',
								MBits: 1,
								DNS: null,
								ReservedPorts: null,
								DynamicPorts: [{ Label: 'http', Value: 27563, To: 0, HostNetwork: 'default' }],
							},
						],
						Devices: null,
					},
					'log-shipper': { Cpu: { CpuShares: 100 }, Memory: { MemoryMB: 300 }, Networks: null, Devices: null },
				},
				TaskLifecycles: { 'log-shipper': null, ark: null },
				Shared: { Networks: null, DiskMB: 300, Ports: null },
			},
			Metrics: {
				NodesEvaluated: 3,
				NodesFiltered: 1,
				NodesAvailable: { 'asia-southeast1': 3 },
				ClassFiltered: null,
				ConstraintFiltered: { '${node.unique.name} regexp nomad-clients-dev.+': 1 },
				NodesExhausted: 0,
				ClassExhausted: null,
				DimensionExhausted: null,
				QuotaExhausted: null,
				Scores: null,
				ScoreMetaData: [
					{
						NodeID: '64cf1f24-7a11-81e1-cb6b-5211424eab8b',
						Scores: {
							binpack: 0.29240429082428343,
							'job-anti-affinity': 0.0,
							'node-reschedule-penalty': 0.0,
							'node-affinity': 0.0,
						},
						NormScore: 0.29240429082428343,
					},
					{
						NodeID: '765c1347-cfb0-c56f-9467-1ed6e416caf5',
						Scores: {
							'node-affinity': 0.0,
							binpack: 0.2798590853341126,
							'job-anti-affinity': 0.0,
							'node-reschedule-penalty': 0.0,
						},
						NormScore: 0.2798590853341126,
					},
				],
				AllocationTime: 200595,
				CoalescedFailures: 0,
			},
			DesiredStatus: 'run',
			ClientStatus: 'running',
			ClientDescription: 'Tasks are running',
			TaskStates: {
				ark: {
					State: 'running',
					Failed: false,
					Restarts: 0,
					LastRestart: null,
					StartedAt: '2021-05-04T03:30:37.668448541Z',
					FinishedAt: null,
					Events: [
						{
							Type: 'Received',
							Time: 1620099029161819111,
							Message: '',
							DisplayMessage: 'Task received by client',
							Details: {},
							FailsTask: false,
							RestartReason: '',
							SetupError: '',
							DriverError: '',
							ExitCode: 0,
							Signal: 0,
							KillTimeout: 0,
							KillError: '',
							KillReason: '',
							StartDelay: 0,
							DownloadError: '',
							ValidationError: '',
							DiskLimit: 0,
							FailedSibling: '',
							VaultError: '',
							TaskSignalReason: '',
							TaskSignal: '',
							DriverMessage: '',
							GenericSource: '',
						},
						{
							Type: 'Task Setup',
							Time: 1620099029171614724,
							Message: 'Building Task Directory',
							DisplayMessage: 'Building Task Directory',
							Details: { message: 'Building Task Directory' },
							FailsTask: false,
							RestartReason: '',
							SetupError: '',
							DriverError: '',
							ExitCode: 0,
							Signal: 0,
							KillTimeout: 0,
							KillError: '',
							KillReason: '',
							StartDelay: 0,
							DownloadError: '',
							ValidationError: '',
							DiskLimit: 0,
							FailedSibling: '',
							VaultError: '',
							TaskSignalReason: '',
							TaskSignal: '',
							DriverMessage: '',
							GenericSource: '',
						},
						{
							Type: 'Driver',
							Time: 1620099029239416944,
							Message: '',
							DisplayMessage: 'Downloading image',
							Details: { image: 'jippi/ark:latest' },
							FailsTask: false,
							RestartReason: '',
							SetupError: '',
							DriverError: '',
							ExitCode: 0,
							Signal: 0,
							KillTimeout: 0,
							KillError: '',
							KillReason: '',
							StartDelay: 0,
							DownloadError: '',
							ValidationError: '',
							DiskLimit: 0,
							FailedSibling: '',
							VaultError: '',
							TaskSignalReason: '',
							TaskSignal: '',
							DriverMessage: 'Downloading image',
							GenericSource: '',
						},
						{
							Type: 'Started',
							Time: 1620099037668442338,
							Message: '',
							DisplayMessage: 'Task started by client',
							Details: {},
							FailsTask: false,
							RestartReason: '',
							SetupError: '',
							DriverError: '',
							ExitCode: 0,
							Signal: 0,
							KillTimeout: 0,
							KillError: '',
							KillReason: '',
							StartDelay: 0,
							DownloadError: '',
							ValidationError: '',
							DiskLimit: 0,
							FailedSibling: '',
							VaultError: '',
							TaskSignalReason: '',
							TaskSignal: '',
							DriverMessage: '',
							GenericSource: '',
						},
					],
				},
				'log-shipper': {
					State: 'running',
					Failed: false,
					Restarts: 0,
					LastRestart: null,
					StartedAt: '2021-05-04T03:30:29.784936995Z',
					FinishedAt: null,
					Events: [
						{
							Type: 'Received',
							Time: 1620099029162229261,
							Message: '',
							DisplayMessage: 'Task received by client',
							Details: {},
							FailsTask: false,
							RestartReason: '',
							SetupError: '',
							DriverError: '',
							ExitCode: 0,
							Signal: 0,
							KillTimeout: 0,
							KillError: '',
							KillReason: '',
							StartDelay: 0,
							DownloadError: '',
							ValidationError: '',
							DiskLimit: 0,
							FailedSibling: '',
							VaultError: '',
							TaskSignalReason: '',
							TaskSignal: '',
							DriverMessage: '',
							GenericSource: '',
						},
						{
							Type: 'Task Setup',
							Time: 1620099029165867709,
							Message: 'Building Task Directory',
							DisplayMessage: 'Building Task Directory',
							Details: { message: 'Building Task Directory' },
							FailsTask: false,
							RestartReason: '',
							SetupError: '',
							DriverError: '',
							ExitCode: 0,
							Signal: 0,
							KillTimeout: 0,
							KillError: '',
							KillReason: '',
							StartDelay: 0,
							DownloadError: '',
							ValidationError: '',
							DiskLimit: 0,
							FailedSibling: '',
							VaultError: '',
							TaskSignalReason: '',
							TaskSignal: '',
							DriverMessage: '',
							GenericSource: '',
						},
						{
							Type: 'Started',
							Time: 1620099029784931474,
							Message: '',
							DisplayMessage: 'Task started by client',
							Details: {},
							FailsTask: false,
							RestartReason: '',
							SetupError: '',
							DriverError: '',
							ExitCode: 0,
							Signal: 0,
							KillTimeout: 0,
							KillError: '',
							KillReason: '',
							StartDelay: 0,
							DownloadError: '',
							ValidationError: '',
							DiskLimit: 0,
							FailedSibling: '',
							VaultError: '',
							TaskSignalReason: '',
							TaskSignal: '',
							DriverMessage: '',
							GenericSource: '',
						},
					],
				},
			},
			DeploymentID: 'eac470d9-f866-16af-194a-ca70e8f71490',
			DeploymentStatus: { Healthy: true, Timestamp: '2021-05-04T03:30:52.166325706Z', Canary: false, ModifyIndex: 285276 },
			CreateIndex: 285270,
			ModifyIndex: 285276,
			AllocModifyIndex: 285270,
			CreateTime: 1620099029135746569,
			ModifyTime: 1620099052246960107,
		});
	},
};
