export interface IFunCaptchaPublicKeys {
	ACTION_TYPE_ASSET_COMMENT: string;
	ACTION_TYPE_CLOTHING_ASSET_UPLOAD: string;
	ACTION_TYPE_GROUP_JOIN: string;
	ACTION_TYPE_GROUP_WALL_POST: string;
	ACTION_TYPE_SUPPORT_REQUEST: string;
	ACTION_TYPE_WEB_GAMECARD_REDEMPTION: string;
	ACTION_TYPE_WEB_LOGIN: string;
	ACTION_TYPE_WEB_RESET_PASSWORD: string;
	ACTION_TYPE_WEB_SIGNUP: string;
}
