CREATE DATABASE IF NOT EXISTS `RobloxAnalytics`;

CREATE TABLE IF NOT EXISTS `RobloxAnalytics`.`Counters` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME NOT NULL,
  `Updated` DATETIME NOT NULL,
  `Name` TEXT NOT NULL,
  `Count` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB;
