CREATE DATABASE IF NOT EXISTS `RobloxAnalytics`;

CREATE TABLE IF NOT EXISTS `RobloxAnalytics`.`Sequences` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `Created` DATETIME NOT NULL,
  `Updated` DATETIME NOT NULL,
  `Name` TEXT NOT NULL,
  `IsNewSequence` BOOLEAN NOT NULL,
  `Value` DOUBLE DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB;
